language: haskell

install:
    - cabal update
    - git clone https://github.com/sol/stringbuilder && cd stringbuilder && cabal install && cd ..
    - cabal install hspec-shouldbe
    - cabal install --enable-tests

script:
    - cabal test
