sudo: false

language: c

env:
  - GHCVER=7.6.3
  - GHCVER=7.8.4
  - GHCVER=7.10.3

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.6.3
      - ghc-7.8.4
      - ghc-7.10.3
      - cabal-install-1.22

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$PATH
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
  - cabal install --enable-tests --only-dep

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
